/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    properties: Property;
    districts: District;
    posts: Post;
    team: Team;
    reviews: Review;
    leads: Lead;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    team: {
      reviews: 'reviews';
    };
  };
  collectionsSelect: {
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    districts: DistrictsSelect<false> | DistrictsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en' | 'tr') | ('ru' | 'en' | 'tr')[];
  globals: {
    company: Company;
    rates: Rate;
    'team-page': TeamPage;
  };
  globalsSelect: {
    company: CompanySelect<false> | CompanySelect<true>;
    rates: RatesSelect<false> | RatesSelect<true>;
    'team-page': TeamPageSelect<false> | TeamPageSelect<true>;
  };
  locale: 'ru' | 'en' | 'tr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  title: string;
  deal: 'sale' | 'rent';
  type: 'apartment' | 'penthouse' | 'villa' | 'duplex' | 'land' | 'commercial';
  district: number | District;
  complex?: string | null;
  rooms?: ('1+0' | '1+1' | '2+1' | '3+1' | '3+2' | '4+1' | '4+2' | '5+1' | '6+1') | null;
  area?: number | null;
  floor?: number | null;
  floors?: number | null;
  year?: number | null;
  sea?: number | null;
  airport?: number | null;
  view?: ('city' | 'sea' | 'mountain' | 'castle') | null;
  furnished?: ('no' | 'yes' | 'partial') | null;
  condition?: ('resale' | 'new' | 'construction') | null;
  source?: ('developer' | 'owner' | 'agency') | null;
  /**
   * В валюте продавца. На сайте — в евро по курсу из настроек.
   */
  priceOriginal?: number | null;
  currency?: ('EUR' | 'USD' | 'GBP' | 'TRY') | null;
  /**
   * Показывается на карточке: «цена проверена 24.09.2026».
   */
  priceCheckedAt?: string | null;
  price?: number | null;
  installment?: {
    months?: number | null;
    down?: number | null;
  };
  bargain?: boolean | null;
  citizenship?: boolean | null;
  residence?: boolean | null;
  rentalIncome?: boolean | null;
  rent?: {
    period?: ('long' | 'short' | 'season') | null;
    pricePerDay?: number | null;
    deposit?: number | null;
    minTerm?: number | null;
    advance?: number | null;
    availableFrom?: string | null;
    utilities?: boolean | null;
    pets?: boolean | null;
  };
  /**
   * Первое фото — обложка. Порядок меняется перетаскиванием.
   */
  photos?: (number | Media)[] | null;
  video?: string | null;
  tour?: string | null;
  /**
   * Абзацы разделяйте пустой строкой. Переключите язык вверху, чтобы добавить EN и TR.
   */
  description?: string | null;
  features?:
    | (
        | 'Открытый бассейн'
        | 'Закрытый бассейн'
        | 'Детский бассейн'
        | 'Аквапарк'
        | 'Фитнес-зал'
        | 'Финская сауна'
        | 'Турецкий хамам'
        | 'Паровая баня'
        | 'Джакузи'
        | 'Массажный кабинет'
        | 'Спа-центр'
        | 'Теннисный корт'
        | 'Баскетбольная площадка'
        | 'Волейбольная площадка'
        | 'Настольный теннис'
        | 'Бильярд'
        | 'Боулинг'
        | 'Кинотеатр'
        | 'Игровая комната'
        | 'Детская площадка'
        | 'Мини-клуб'
        | 'Кафе / ресторан'
        | 'Бар у бассейна'
        | 'Маркет'
        | 'Парикмахерская'
        | 'Конференц-зал'
        | 'Зелёная территория'
        | 'Прогулочные дорожки'
        | 'Зоны барбекю'
        | 'Беседки'
        | 'Собственный пляж'
        | 'Шаттл до пляжа'
        | 'Охрана 24/7'
        | 'Видеонаблюдение'
        | 'Консьерж'
        | 'Генератор'
        | 'Крытая парковка'
        | 'Открытая парковка'
        | 'Лифт'
        | 'Спутниковое ТВ'
        | 'Wi-Fi на территории'
        | 'Тёплый пол'
        | 'Кондиционеры'
        | 'Встроенная кухня'
        | 'Солнечный водонагреватель'
      )[]
    | null;
  lat?: number | null;
  lng?: number | null;
  /**
   * Только для сотрудников, на сайте не показывается.
   */
  address?: string | null;
  seo?: {
    /**
     * Пусто — «Заголовок · Район · цена».
     */
    title?: string | null;
    description?: string | null;
  };
  status: 'published' | 'draft' | 'reserved' | 'sold' | 'rented' | 'hidden';
  /**
   * Пусто — распределяется между экспертами автоматически.
   */
  agent?: (number | null) | Team;
  labels?: ('week' | 'hot' | 'rec' | 'excl')[] | null;
  /**
   * Латиницей через дефис. Пусто — заполнится из заголовка.
   */
  slug?: string | null;
  /**
   * Контакты собственника, ключи, комиссия. На сайте не видно.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Районы Аланьи для каталога и страниц /districts/. Порядок — с запада на восток.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts".
 */
export interface District {
  id: number;
  name: string;
  /**
   * Для заголовков: «Квартиры в Махмутларе».
   */
  nameIn?: string | null;
  slug: string;
  order?: number | null;
  inland?: boolean | null;
  about?: string | null;
  lead?: string | null;
  pros?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cons?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  infra?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Ориентир для страницы района и калькулятора.
   */
  pricePerM2?: number | null;
  pricePerM2Date?: string | null;
  /**
   * Минус — на запад от центра.
   */
  coastKm?: number | null;
  scores?: {
    life?: number | null;
    rent?: number | null;
    beach?: number | null;
    infra?: number | null;
    quiet?: number | null;
  };
  lat?: number | null;
  lng?: number | null;
  /**
   * Координаты на рисованной схеме (1000×440) на главной и в гиде.
   */
  schema?: {
    x?: number | null;
    y?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Что на фото, для поисковиков и незрячих: «Гостиная с видом на море».
   */
  alt?: string | null;
  credit?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Порядок в списке = порядок на странице «Команда». Скрытые не показываются на сайте, их объекты распределяются между экспертами.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  kind: 'founder' | 'expert' | 'lawyer';
  langs?: string | null;
  exp?: number | null;
  photo?: (number | null) | Media;
  areas?: (number | District)[] | null;
  spec?: string | null;
  bio?: string | null;
  help?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  whatsapp?: string | null;
  telegram?: string | null;
  email?: string | null;
  /**
   * Латиницей через дефис. Пусто — заполнится из заголовка.
   */
  slug?: string | null;
  order?: number | null;
  hidden?: boolean | null;
  reviews?: {
    docs?: (number | Review)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  who: string;
  country?: string | null;
  date: string;
  rating: number;
  service?: ('buy' | 'rent' | 'docs' | 'sell') | null;
  expert?: (number | null) | Team;
  /**
   * На языке клиента, без перевода.
   */
  text: string;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Статьи (блог) и новости. Дата в будущем — публикация появится на сайте в этот день.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  kind: 'article' | 'news';
  category: 'market' | 'laws' | 'residence' | 'life' | 'rates' | 'agency';
  lead?: string | null;
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Для новостей о законах, ВНЖ и курсах — обязательно (сайт ведомства).
   */
  source?: string | null;
  reviewedAt?: string | null;
  tags?: string[] | null;
  relatedDistricts?: (number | District)[] | null;
  relatedProperties?: (number | Property)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  publishedAt: string;
  /**
   * Пусто — «Редакция Kleo Homes».
   */
  author?: (number | null) | Team;
  pinned?: boolean | null;
  /**
   * Латиницей через дефис. Пусто — заполнится из заголовка.
   */
  slug?: string | null;
  readingMins?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Статусы нужны для отчёта по рекламе: какие заявки дошли до просмотра и сделки.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  contactVia?: ('whatsapp' | 'telegram' | 'phone' | 'email') | null;
  form?: ('pick' | 'viewing' | 'question' | 'cheaper' | 'costs' | 'consult' | 'sell') | null;
  locale?: string | null;
  message?: string | null;
  property?: (number | null) | Property;
  page?: string | null;
  /**
   * Откуда пришёл посетитель: заполняется автоматически.
   */
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    term?: string | null;
    content?: string | null;
    gclid?: string | null;
  };
  consent?: boolean | null;
  status?: ('new' | 'work' | 'viewing' | 'deal' | 'lost' | 'spam') | null;
  agent?: (number | null) | Team;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'agent';
  /**
   * Для роли «Агент»: какие объекты и заявки ему доступны.
   */
  member?: (number | null) | Team;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'districts';
        value: number | District;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  title?: T;
  deal?: T;
  type?: T;
  district?: T;
  complex?: T;
  rooms?: T;
  area?: T;
  floor?: T;
  floors?: T;
  year?: T;
  sea?: T;
  airport?: T;
  view?: T;
  furnished?: T;
  condition?: T;
  source?: T;
  priceOriginal?: T;
  currency?: T;
  priceCheckedAt?: T;
  price?: T;
  installment?:
    | T
    | {
        months?: T;
        down?: T;
      };
  bargain?: T;
  citizenship?: T;
  residence?: T;
  rentalIncome?: T;
  rent?:
    | T
    | {
        period?: T;
        pricePerDay?: T;
        deposit?: T;
        minTerm?: T;
        advance?: T;
        availableFrom?: T;
        utilities?: T;
        pets?: T;
      };
  photos?: T;
  video?: T;
  tour?: T;
  description?: T;
  features?: T;
  lat?: T;
  lng?: T;
  address?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  status?: T;
  agent?: T;
  labels?: T;
  slug?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts_select".
 */
export interface DistrictsSelect<T extends boolean = true> {
  name?: T;
  nameIn?: T;
  slug?: T;
  order?: T;
  inland?: T;
  about?: T;
  lead?: T;
  pros?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        text?: T;
        id?: T;
      };
  infra?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  pricePerM2?: T;
  pricePerM2Date?: T;
  coastKm?: T;
  scores?:
    | T
    | {
        life?: T;
        rent?: T;
        beach?: T;
        infra?: T;
        quiet?: T;
      };
  lat?: T;
  lng?: T;
  schema?:
    | T
    | {
        x?: T;
        y?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  category?: T;
  lead?: T;
  cover?: T;
  body?: T;
  source?: T;
  reviewedAt?: T;
  tags?: T;
  relatedDistricts?: T;
  relatedProperties?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  publishedAt?: T;
  author?: T;
  pinned?: T;
  slug?: T;
  readingMins?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  kind?: T;
  langs?: T;
  exp?: T;
  photo?: T;
  areas?: T;
  spec?: T;
  bio?: T;
  help?:
    | T
    | {
        text?: T;
        id?: T;
      };
  phone?: T;
  whatsapp?: T;
  telegram?: T;
  email?: T;
  slug?: T;
  order?: T;
  hidden?: T;
  reviews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  who?: T;
  country?: T;
  date?: T;
  rating?: T;
  service?: T;
  expert?: T;
  text?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  contactVia?: T;
  form?: T;
  locale?: T;
  message?: T;
  property?: T;
  page?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
        gclid?: T;
      };
  consent?: T;
  status?: T;
  agent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  member?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: number;
  phone: string;
  whatsapp: string;
  telegram?: string | null;
  email: string;
  address: string;
  showroom?: string | null;
  hours?: string | null;
  lat?: number | null;
  lng?: number | null;
  legal?: {
    name?: string | null;
    license?: string | null;
    verbis?: string | null;
    taxOffice?: string | null;
    taxNo?: string | null;
  };
  officePhoto?: (number | null) | Media;
  licensePhoto?: (number | null) | Media;
  awards?: string | null;
  social?:
    | {
        network?: ('instagram' | 'youtube' | 'facebook' | 'vk' | 'tiktok' | 'telegram') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  isDemo?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Сколько единиц валюты стоит 1 €.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates".
 */
export interface Rate {
  id: number;
  USD: number;
  TRY: number;
  RUB: number;
  KZT: number;
  GBP: number;
  checkedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page".
 */
export interface TeamPage {
  id: number;
  title: string;
  lead?: string | null;
  /**
   * Без кавычек. Пусто — цитата не показывается.
   */
  quote?: string | null;
  /**
   * Пустое значение — посчитать автоматически (число сотрудников на сайте).
   */
  stats?:
    | {
        value?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  phone?: T;
  whatsapp?: T;
  telegram?: T;
  email?: T;
  address?: T;
  showroom?: T;
  hours?: T;
  lat?: T;
  lng?: T;
  legal?:
    | T
    | {
        name?: T;
        license?: T;
        verbis?: T;
        taxOffice?: T;
        taxNo?: T;
      };
  officePhoto?: T;
  licensePhoto?: T;
  awards?: T;
  social?:
    | T
    | {
        network?: T;
        url?: T;
        id?: T;
      };
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates_select".
 */
export interface RatesSelect<T extends boolean = true> {
  USD?: T;
  TRY?: T;
  RUB?: T;
  KZT?: T;
  GBP?: T;
  checkedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page_select".
 */
export interface TeamPageSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  quote?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}